### ISSUE TITLE
Table rows - $lighter-grey looks weird on certain page backgrounds

### ISSUE THREAD

**Issue by drawcard** [elementor/hello-theme#146]
Hello,

The lighter-grey shade works fine when the page background is white, however if the page background is another colour, the alternating table row styles look odd:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/1435638/107908313-a72d8f80-6fa5-11eb-85b5-454a2293d38f.png">

```css
table tbody>tr:nth-child(odd)>td, table tbody>tr:nth-child(odd)>th {
    background-color: #f7f7f7;
}
```

Perhaps the same effect can be achieved with a tinted RGBA value, so that the row styles integrate better with coloured page backgrounds:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/1435638/107909285-c5948a80-6fa7-11eb-92ff-864089a993d4.png">

```css
table tbody>tr:nth-child(odd)>td, table tbody>tr:nth-child(odd)>th {
    background-color: rgba(128,128,128,0.15);
}
```
