### ISSUE TITLE
Table cells - grey outlines stand out oddly

### ISSUE THREAD

**Issue by drawcard** [elementor/hello-theme#147]
Related to: #146 which I just raised - it would be nice if table cell outlines also used RGBA to be tinted, so they better integrate into coloured page backgrounds:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/1435638/107908787-c4169280-6fa6-11eb-9ec4-8b3f09ebf7d2.png">

```css
table td, table th {
    padding: 15px;
    line-height: 1.5;
    vertical-align: top;
    border: 1px solid rgba(128,128,128,0.15);
}
```

Although this is a very similar grey to the original, it blends in slightly better with various colours and also stands out on dark backgrounds.
